### PR TITLE
Harder Better Faster Stronger... V3

### PR DESCRIPTION
**Pull request by seyDoggy**
Ok, so I decided to scrap v2 and do a complete and total rewrite (again).
- there is only ever one .superbox-show DOM element created,  
- it's inserted after the entire row you happened to be clicked on and stays in the right place even after a window resize  
- there is now keyboard navigation
- scrolling takes you to the top of the row of images (your original intent I believe)
- usage and all v2 options and features are intact

I think v3 is the one worth building on. Ignore the v2 pull request.

### CODE REVIEW

**Comment by macsupport** [comment]
I am seeing a bug in both Firefox and Safari. Open a Superbox and then click on adjacent thumbs, the same, original superbox image loads each time, not the new adjacent clicked thumb image.

**Comment by toddmotto** [comment]
Can confirm that, when you click on any other image, it fades out the current image, then fades it back in, then loads the image you've clicked on. Almost like the events are in the wrong order.

**Comment by toddmotto** [comment]
What do you think to previous/next links to take you to the next image? I reckon that would be a handy include! :)

**Comment by seyDoggy** [comment]
The image transition problem is due to animation queue and load times for the images. I'm working on preloading the previous and next images into the DOM so that they are cached by the time they are requested.

Any yes prev/next navigation is the next thing I want to add.

**Comment by macsupport** [comment]
Bug in iOS landscape orientation. Superbox image does not scroll into viewport. Seems ok in portrait mode.

**Comment by seyDoggy** [comment]
In v2 I had the lighbox area scroll to the center of the viewport. I realized that Todd's original intent was to have it scroll to the top of the row instead, so that's what I did with v3. Which makes a lot of sense in most cases. Obviously landscape on iOS is not one of those cases where it makes sense.  

Open an issue on my fork and I'll write up some logic for it next week.  

## 

Adam Merrifield
seyDoggy vCard: seyDoggy.com/vcard

**Comment by seyDoggy** [comment]
Ok, I've added navigation, vastly improved preloading with additional lazy loading on mouseenter event and now setting the layout based on superbox container width instead of window width. http://seydoggy.com/dem/superbox

Any idea on if/when you might pull this branch?

**Comment by toddmotto** [comment]
Hey Adam. I'll get this merged over the next week or so, I'm waiting for my new broadband to connect and as such have no access at home until further notice! :)

**Comment by josiahwiebe** [comment]
Has this been merged into master yet?

**Comment by seyDoggy** [comment]
Not that I know of. I keep my version pretty current though. 

Adam Merrifield
vCard: seydoggy.com/vcard

**Comment by toddmotto** [comment]
I won't be updating this version for a while, I'd suggest Adam's Repo for any future updates, closing off - thx guys.

**Pull request closed without merging**
