### PR TITLE
Completely rewrote the plugin

### PR DESCRIPTION
**Pull request by seyDoggy**
Completely rewrote the plugin to make it easier to use and implement and made the operation much smoother and more fluid. Added options to make the plugin more flexible. Removed class name dependency. Added a manual.

### CODE REVIEW

**Comment by toddmotto** [comment]
Thanks Adam, this looks great. I have a few thoughts and suggestions:

1) All images (including full-size ones) are all downloaded on page load. Whereas before they were downloaded onclick. From a performance perspective, downloading all images is going to hang the page for a while, I've included three rows of images which is over 1.5MB, already a resource - especially on non-desktop devices.

2) Generated markup, not a huge issue, but the markup is dynamically generated creating a &lt;div class=superbox-show&gt; for each image on the page, which again will add to the resources loading the page. The current superbox uses one image 'reveal' which moves around the page with you.

The script itself is nifty though and appreciate the Fork and Pull. What do you think on the above? :-)

**Comment by seyDoggy** [comment]
1) Not really on page load but document ready. So in reality if the script as called at the closing body then the page will load as expected and then the full images would be loaded dynamically after the fact. But yeah, this could cause some serious slow downs. I'll look at loading them on click instead, but with with a little more finesse so that the load is proceeded by a load gif while waiting.

2) Generating markup is so cheap that in the interest of fluidity I felt it was worth pre-populating the markup before hand. That way you iterate through the DOM once in this regard instead of creating then destroying markup on each event. It's just a personal preference, but if you'd rather it was created and destroyed we can work on that too.

My priority was to get the beginnings of a user interface (options) and the have smoothest experience possible, one that was worthy of a "lightbox re-imagined" moniker. If you think it can be more efficient still (always room) then let's look at doing that too. I think there is some really nice potential in the idea and want to see it become something great all around.

**Comment by toddmotto** [comment]
Hey Adam. Yep, not massively worried about 2) as markup is pretty lightweight, but on an extreme gallery - you know what people and clients are like ;-) it could cause some jittering/lag...

But definitely 1). I think the way I had it setup, would load the image, and try animating at the same time, which admittedly gave a slight bump whilst trying to animate as it then renders the image. To overcome this, I really like your idea of loading/exposing the image and then shortly after animate up. I love the overall smoothness too so great job. I think integrating an AJAX loader/spinner to take hold before the image loads (onclick) is a next-phase include, that's been my next include I just haven't had time recently, but the potential is there. Appreciate your help with this and wanting to help with the project :-)

One thing I have noticed, when Dev Tools is open, or the 'downloads' bar at the bottom is, it doesn't seem to scroll to the top of the image row properly, more like half-way down the image row.

**Comment by seyDoggy** [comment]
Yeah not really sure why, but you can use outerHeight(true) in that case, but the calcs weren't always consistent there either. Worth looking into more.

I'll look at lazy loading full images this week.

**Comment by seyDoggy** [comment]
Ok, images are now lazy loaded.

**Comment by toddmotto** [comment]
Hey Adam. Am following your progress on this, I apologise I don't have time over the next few weeks to help develop this. For some reason the scroll to top still doesn't like it on Chrome, weird. Lazy loading looks very nice, I'm not sure about the full screen image though - distorts the nice and sharp pics :(! Thanks again. Looking forward to relaunching this with your includes! One thing I've debated from the start is the position of the close button, and maybe whether it deserves it's own background to stand out in front of the image (gets lost in some admittedly). What're your thoughts on that? Other option is to create more of a gap on left/right margins to make room - but this hinders the image dimensions on smaller devices!

**Comment by seyDoggy** [comment]
No worries about helping, I'm having fun just the same.

> For some reason the scroll to top still doesn't like it on Chrome, weird. 

I've check in Firefox, Opera, Chrome desktop/iOS and Safari desktop/iOS (haven't checked IE in a few commits) and I get the same behavior across all versions since commit #75bc88e. I suppose the question is what behavior are you expecting? I have the superbox-show div going exactly centered but perhaps your expecting a different behavior? Is it the top of the clicked thumbnail you expect and the top of the screen?

> I'm not sure about the full screen image though - distorts the nice and sharp pics

In #2a2544b I added a 600px height limit, but then swapped that with a viewport limit instead. But I can add a few more decision trees to test the image-actual and adjust accordingly. Ideally what I'm trying to do is make a known superbox-show size to aid in the transition from one to the other without the page collapsing and things jumping all about. I could also add a user option that allows the max-height to be set.

> One thing I've debated from the start is the position of the close button, and maybe whether it deserves it's own background to stand out in front of the image (gets lost in some admittedly). What're your thoughts on that?

Keep in mind that the x-icon is text and it's color and text shadow is adjustable in the SuperBox options:

``` js
$.SuperBox({
    background : '#FF0000', // Full image background color. Default: #333
    border : 'white', // Full image border color. Default: #222
    xColor : '#CCC', // Close icon color. Default: #FFF
    xShadow : 'embed' // Close icon shadow. Default: none
});
```

But that said, it wouldn't take much to add a background and some options there as well. xBackground perhaps.

**Comment by macsupport** [comment]
One other option to consider adding to the plugin is an image caption, using data-caption possibly? Just a thought...

**Comment by seyDoggy** [comment]
No need to use data-caption, using alt would suffice. I'll look into it.

Adam Merrifield
seyDoggy vCard: seyDoggy.com/vcard

**Comment by toddmotto** [comment]
I'd potentially be open to a data-\* attribute, using Alt seems a little ...wrong - only because the 'proper' alternate text supplied for the image (to semantically provide the role the alt attribute does in a production scenario) might not be the right context - an image caption/title may be something completely random. data-title and data-description (maybe data-desc for brevity) could be good. But I think 'standard' attributes feel a little hacky, especially as it's not their proper use case! Happy to take a view though! :)

**Comment by macsupport** [comment]
I agree. Many instances where an alt attribute would not be the choice for a caption for the full size image.

**Comment by seyDoggy** [comment]
I'm completely rewriting the plugin (again, v3, lol) so I'll keep data-desc in mind. Though from a end-user standpoint, the alt attribute is likely to make more sense and is something they should be filling in in the first place. The alt attribute is, by definition, to specify alternative text (alt text) that is to be rendered when the element to which it is applied cannot be rendered (or seen in the case of screen readers)... essentially a description of the missing or unseen image. It's tough to ask people to enter a separate description in data-desc when chances are their alt attribute will be exactly that.

**Comment by toddmotto** [comment]
Yeah, that's true - but there are cases where alt text isn't required and can be left empty, it again depends on the context, and as there are no strict 'rules' to alt text and it's openly interpreted depending on use case, you could argue that is a good thing for the plugin/dev perspective, but bad for consistency! As long as each image is shipped with a blank alt="" by default that should be fine, leaving the user to fill in each one should they need and wish to :D

**Comment by seyDoggy** [comment]
Alt text on images is always required to conform to wcag and HTML4.01+ standards.  

## 

Adam Merrifield
seyDoggy vCard: seydoggy.com/vcard

**Comment by toddmotto** [comment]
Physical text isn't, but the attribute is required.

**Comment by seyDoggy** [comment]
While it could be argued that a gallery is "purely decorative" I think most would argue that it's functional, and therefor alt text is required.

## 4.1.2 Using an empty alt attribute alt=""

### Circumstances in which it is appropriate to use an empty or null alt attribute:
- An image is purely decorative.
- An image is not meant to be visible to any user.
- An image consists of text that is repeated as text or a graphical symbol whose meaning is conveyed as text, immediately before or after the image.
- The image is part of a group of images that form a single larger picture and one of the other images in the group has a text alternative which serves as the text alternative for the single larger picture.
- The image is included as the content of a link and there is other content included that clearly describes the link target.

### Circumstances in which it is not appropriate to use an empty or null alt attribute:
- An image is contained within a figure element and has an associated caption provided using the figcaption element. Using an empty alt attribute hides an image from some users. If an image has a caption the image needs to be discoverable by users, otherwise a caption is present that refers to nothing for some users.
- An image contains relevant information not available in the same document as text. Using an empty alt attribute hides an image from some users. In order to have the possibility of interrogating the image, the image must be discoverable.
- An image contains relevant information, an alternative interpretation of which is available in the same document as structured text. Using an empty alt attribute hides an image from some users, which is incorrect. The image is not meaningless, it contains information which a range of users could interpret with the aid of the short text alternative and longer description. It also provides a text alternative for users who have images turned off in their browsers, so they can, if they wish, load and view the image. If an empty alt attribute is present there may be no indication that an image is present. Furthermore if a description of an image is provided in a document, a programmatic association between the image and the descriptive text is required. Using an empty alt attribute on the image effectively precludes the assigning of a programmatic association."  

## 

Adam Merrifield
seyDoggy vCard: seydoggy.com/vcard

**Pull request closed without merging**
